spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret:  ${GITHUB_CLIENT_SECRET}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    url: jdbc:postgresql://localhost:5432/healthcent
    password: secret
  jpa:
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: 'true'
      database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

allowed-origins: http://localhost:3000
default-error: http://localhost:3000/error
default-success: http://localhost:3000/home